FROM node:22-alpine

WORKDIR /usr/src/app

# Install openssl for Prisma compatibility with Alpine
RUN apk add --no-cache openssl

COPY package*.json ./

RUN npm install

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
